[options]

db_host = postgres.railway.internal
db_port = 5432
db_user = myodoo
db_password = mypassword

addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/extra-addons/enterprise

workers = 2
max_cron_threads = 1

proxy_mode = True

list_db = False