[options]

db_host = False
db_port = False
db_user = False
db_password = False

addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/extra-addons/enterprise

workers = 2
max_cron_threads = 1

proxy_mode = True

list_db = False